### ISSUE TITLE
Download latest official version at admin.mobilpay.ro

### ISSUE THREAD

**Issue by alexminza** [mobilpay/Opencart#1]
You can download the latest version at https://admin.mobilpay.ro/implement/admin/download-example/docId/34544

This repository is not actively maintained by the organization/developer https://github.com/mobilpay/opencart/commits/master

PS: https://twitter.com/AlexMinza/status/794515493260562432
PPS: https://www.facebook.com/alexminza/posts/10154781121003083

**Comment by fixone** [comment]
This comment refers to a previous version of this module. We have now updated the code with the latest available versions. If you find any problems feel free to submit a PR

**Comment by alexminza** [comment]
@fixone Thank you for updating the code!

This issue was referring to the repository in general that it was not maintained and to not confuse the developers/implementers looking for the mod.

It would be great if you could move the code of the mods to a public repository like GitHub to allow the developers to monitor the updates, review the changes and fixes, maybe even contribute to the code. I do believe more transparency could benefit all of the participants.
