### ISSUE TITLE
problem with installation on Opencart 2.1.0.2.

### ISSUE THREAD

**Issue by MAGICLED** [mobilpay/Opencart#14]
Hello,

I followed all the steps from Installation, but when I went to Configuration, Mobilpay Romania extension doesn't appear in the Extensions-Payment area.

What should I do?

Thank you,
Cristina M

**Comment by navid59** [comment]
Sorry, for late answering you.
Is appear in "Other" section area.
By clicking in other, you can find it in the list and continue the configuration.
