### ISSUE TITLE
Decriptarea datelor a esuat!

### ISSUE THREAD

**Issue by discadaniel** [mobilpay/Opencart#15]
Am urmat toti pasii necesari.... nu merge pe niciun mediu, nici sandbox nici live

Decriptarea datelor a esuat!

**Comment by discadaniel** [comment]
pentru 1.5.x-1.9.x

**Comment by rootyoo82** [comment]
Buna ziua, aceiasi eroare o primesc si eu, Op 3.0.3.8

**Comment by mativesolutions** [comment]
Da, pare sa fie problema de la openSSL, dupa upgrade la de la openSSL 1.x.x la 3.x.x avem si noi aceeasi problema...

**Comment by nt77alb** [comment]
Salut, ati rezolvat cumva problema? Multumesc!

**Comment by navid59** [comment]
The issue with OpenSSL versions 1.x.x and 3.x.x has already been resolved.
Please update your application.

If you still encounter issues with OpenSSL, please contact us at implementare@netopia-payments.com

Thank you
