### ISSUE TITLE
Undefined variable: worldpay_geo_zone_id in admin/view/template/extension/payment/mobilpay.tpl on line 151

### ISSUE THREAD

**Issue by alexminza** [mobilpay/Opencart#2]
Undefined variable: worldpay_geo_zone_id in admin/view/template/extension/payment/mobilpay.tpl on line 151 https://github.com/mobilpay/Opencart/blob/master/v.2.3.x/admin/view/template/extension/payment/mobilpay.tpl#L151

Url: /admin/index.php?route=extension/payment/mobilpay

**Comment by andreipanait** [comment]
Fixed 56a302716b7a9e10d34c8ff7f56ecdf9a94c670a
